# Site settings
name: Yunus Emre EKİNCİ
description: ""
# description: "merhaba bana sosyal medyadan ulaşabilir yada e postadan merhaba diyebilirsiniz. Blogumu açtım bakabilirsiniz. 
#muhasebe #smmm #cpa #audit #denetim #KDV #kdviadesi #vergi #iade
#php #kodlama #teknoloji #yazılım #programlama "
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
twitter_username: emrex
facebook_username: eekincicom
linkedin_username: eekincicom
instagram_username:  eekincicom
email: bilgi@eekinci.com?subject=merhaba
blog_url: "/nobelium"
# github_username:  webtasarim70
# codepen_username: your_codepen_username_goes_here
# vk_username: your_vk_username_goes_here
# google_plus_username: your_google_plus_username_goes_here
# vine_username:  your_vine_username_goes_here
# flickr_username: your_flickr_username_goes_here
# steam_username: your_steam_username_goes_here
# soundcloud_username:  your_soundcloud_username_goes_here
# stack_of_username: your_stack_overflow_account_id_number_goes_here
# reddit_username: your_reddit_username_goes_here
# medium_username:  your_medium_username_goes_here
# tumblr_username: your_tumblr_username_goes_here
# weibo_username: your_weibo_username_goes_here
# lastfm_username: your_lastfm_username_goes_here
# blog_url: "/blog"
# public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars3.githubusercontent.com/u/27343458"


front_img: yes
#front_img_path: "imgs/background.jpg"
#front_img_path: "https://images.unsplash.com/photo-1466220666686-90bdba318c9a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1360&q=80"

front_img_path: "https://images.unsplash.com/photo-1568678090873-3bd8c9c336b0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
